name: release
on:
  release:
    types: [published]

jobs:
  independent-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform independent task
        run: echo "This job runs independently of other jobs."
  release-job:
    needs: ["Formatting", "Tests"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: false
          tags: simonsobs/librarian:${{ github.event.release.tag_name }}
